export const AmenitiesData: string[] = [
  "Air conditioning",
  "Heating",
  "WiFi",
  "Parking",
  "Garage",
  "CCTV",
  "Elevator",
  "Refrigerator",
  "Shower",
  "Jacuzzi",
  "Gym",
  "Garden",
  "Waste disposal",
  "Oven",
  "Stove",
  "Microwave",
  "Cooling",
  "Cabel",
  "Televison",
  "Swimming Pool",
  "Smoke detector",
  "Dog park",
  "Fence",
  "Elevtor",
  "Alarm",
].sort((a, b) => a.localeCompare(b));
